language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - composer test


matrix:
  allow_failures:
    - php: nightly
